spring:
  application:
    name: aggregator
  datasource:
    url: jdbc:mysql://localhost:3307/stay_aggregator
    username: root
    password: local
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

supplier:
  a:
    base-url: http://localhost:9090/a
  b:
    base-url: http://localhost:9090/b
